<?php
session_start();
?>
<h1> CALCULADORA </h1>

<!--<div class="table-responsive">-->
<table class="table">
    <tr>
        <th>
            <?php
            echo "<input type='number' id='number' value='0' />";
            ?>       
        </th>
    </tr>
    <tr>
        <td>
            <div>
                <div class="btn-group">
                    <button type="button" id="addBtn" class="btn btn-default" >
                        +
                    </button>
                    <button type="button" id="divisionBtn" class="btn btn-default">
                        /
                    </button>
                    <button type="button" id="equalBtn" class="btn btn-default">
                        =
                    </button>

                </div> <br>
                <div class="btn-group">
                    <button type="button" id="cleanLocal" class="btn btn-default">
                        CLM
                    </button>
                    <button type="button" id="cleanServer" class="btn btn-default">
                        CSM
                    </button>
                </div><br>
                <div class="btn-group">
                    <button type="button" id="btn7" class="btn btn-default">
                        7
                    </button>
                    <button type="button" id="btn8" class="btn btn-default">
                        8
                    </button>
                    <button type="button" id="btn9" class="btn btn-default">
                        9
                    </button>
                </div><br>

                <div class="btn-group">
                    <button type="button" id="btn4" class="btn btn-default">
                        4
                    </button>
                    <button type="button" id="btn5" class="btn btn-default">
                        5
                    </button>
                    <button type="button" id="btn6" class="btn btn-default">
                        6
                    </button>
                </div><br>
                <div class="btn-group">
                    <button type="button" id="btn1" class="btn btn-default">
                        1
                    </button>
                    <button type="button" id="btn2" class="btn btn-default">
                        2
                    </button>
                    <button type="button" id="btn3" class="btn btn-default">
                        3
                    </button>
                </div><br>
                <div class="btn-group">
                    <button type="button" id="btn0" class="btn btn-default">
                        0
                    </button>
                </div>
            </div>
        </td>
    </tr>


</table>
<!--</div>-->